### ISSUE TITLE
CentOS 6.4 32bit - uno.DisposedException: Binary URP bridge disposed during call

### ISSUE THREAD

**Issue by Jimbobnz** [dagwieers/unoconv#158]
I am unable to run unoconv on CentOS 6.4 32bit (works fine under CentOS 6.4 64bit). I get the following errors:

``` bash
# unoconv -vvvv -f pdf test.txt
Verbosity set to level 4
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1162, in <module>
    main()
  File "/usr/bin/unoconv", line 1079, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 716, in __init__
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call
```

``` bash
#  unoconv --version
unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.6.6 (r266:84292, Jul 10 2013, 22:43:23)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
LibreOffice 3.4
```

**Comment by dagwieers** [comment]
We don't know what the cause of this is currently. Could you try this with a newer version of unoconv and LibreOffice ? Thanks !

**Comment by dagwieers** [comment]
Seel also #57

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
