### ISSUE TITLE
Issue when converting Word document

### ISSUE THREAD

**Issue by MirkoCindric** [dagwieers/unoconv#176]
When trying to convert a word document l get

```
unoconv: RuntimeException during import phase:
Office probably died. Binary URP bridge disposed during call
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1167, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 1027, in die
    if convertor.desktop.getCurrentFrame():
uno.RuntimeException: illegal object given!
```

Am running the following specs

```
unoconv 0.6
platform posix/darwin
python 2.6.1 (r261, Jul  9 2013, 06:34:54) 
[GCC 4.0.1 (Apple Inc. build 5494)]
LibreOffice 3.6
```

Seems to be an issue with the docx file. Client created it and loads fine in work but noticed the tags are different

This is the failing one

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" mc:Ignorable="w14"><w:body><w:p><w:pPr><w:pStyle w:val="Date and Recipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:b w:val="1"/><w:bCs w:val="1"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:b w:val="1"/><w:bCs w:val="1"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t>DETENTION NOTICE</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Date and Recipient"/><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t>Date: {{ date}}</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Date and Recipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t>{{ recipient}}</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Date and Recipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t xml:space="preserve">Please report for {{ detention type}} on </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t>{{ completion-date }}</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Closing"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:cs="Arial Narrow" w:hAnsi="Arial Narrow" w:eastAsia="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/><w:rtl w:val="0"/><w:lang w:val="en-US"/></w:rPr><w:t>Reason for this notice {{ reason}}</w:t></w:r></w:p><w:sectPr><w:headerReference w:type="default" r:id="rId4"/><w:headerReference w:type="first" r:id="rId5"/><w:footerReference w:type="default" r:id="rId6"/><w:footerReference w:type="first" r:id="rId7"/><w:pgSz w:w="12240" w:h="15840" w:orient="portrait"/><w:pgMar w:top="720" w:right="1440" w:bottom="720" w:left="1440" w:header="720" w:footer="720"/><w:titlePg w:val="1"/><w:bidi w:val="0"/></w:sectPr></w:body></w:document>
```

And when l open and just hit save in my word it comes out like so

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14"><w:body><w:p w14:paraId="05D54159" w14:textId="77777777" w:rsidR="000408BA" w:rsidRDefault="002E0A3B"><w:pPr><w:pStyle w:val="DateandRecipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:b/><w:bCs/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:b/><w:bCs/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr><w:t>DETENTION NOTICE</w:t></w:r></w:p><w:p w14:paraId="6138A5E8" w14:textId="77777777" w:rsidR="000408BA" w:rsidRDefault="002E0A3B"><w:pPr><w:pStyle w:val="DateandRecipient"/><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr><w:t>Date: {{ date }}</w:t></w:r><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/></w:p><w:p w14:paraId="5541A66C" w14:textId="77777777" w:rsidR="000408BA" w:rsidRDefault="002E0A3B"><w:pPr><w:pStyle w:val="DateandRecipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr><w:t>{{ recipient }}</w:t></w:r></w:p><w:p w14:paraId="529A61B6" w14:textId="3665CAEE" w:rsidR="000408BA" w:rsidRDefault="00C33F98"><w:pPr><w:pStyle w:val="DateandRecipient"/><w:tabs><w:tab w:val="left" w:pos="8640"/></w:tabs><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr><w:t xml:space="preserve">Please report for {{ detention type}} on {{ completion </w:t></w:r><w:r w:rsidR="002E0A3B"><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:color w:val="000000"/><w:sz w:val="28"/><w:szCs w:val="28"/><w:u w:color="000000"/></w:rPr><w:t>date }}</w:t></w:r></w:p><w:p w14:paraId="07A37337" w14:textId="77777777" w:rsidR="000408BA" w:rsidRDefault="002E0A3B"><w:pPr><w:pStyle w:val="Closing"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial Narrow" w:eastAsia="Arial Narrow" w:hAnsi="Arial Narrow" w:cs="Arial Narrow"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr><w:t>Reason for this notice {{ reason }}</w:t></w:r></w:p><w:sectPr w:rsidR="000408BA"><w:headerReference w:type="default" r:id="rId7"/><w:footerReference w:type="default" r:id="rId8"/><w:headerReference w:type="first" r:id="rId9"/><w:footerReference w:type="first" r:id="rId10"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="1440" w:bottom="720" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/><w:cols w:space="720"/><w:titlePg/></w:sectPr></w:body></w:document>
```

Notice all the extra tags in there now and some tags removed. Seems unoconv doesnt like this at all

**Comment by dagwieers** [comment]
What is the command you are running ?
What file are you using ?
What version of unoconv and LibreOffice are being used ?

Without any of this information I don't know where to begin.
If you need more hints to analyze this yourself, please look at the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions).

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
