### ISSUE TITLE
Installation of unoconv on Windows 7 running latest LibreOffice 4.4

### ISSUE THREAD

**Issue by HaakonME** [dagwieers/unoconv#240]
I installed LibreOffice 4.4 and downloaded the unoconv ZIP-archive from GitHub today, 2015-02-04. 
I unpacked unoconv, then put all files from the archive into C:\unoconv. I have not added any environment variables. LibreOffice 4.4 installed with Python 3.3.5 at C:\Program files\LibreOffice 4\. soffice.exe and python.exe is then in C:\Program files\LibreOffice 4\program.

Issuing at a command prompt

c:\unoconv>"C:\Program Files\LibreOffice 4\program\python.exe" unoconv -f pdf tests\document-example.odt

results in a dialogue box appearing saying LibreOffice has stopped working, and you get to close the program. 

In the command prompt window, the command seems to be still running.

Using the process manager soffice was found still running. Stopping the process tree with the process manager, the following error message becomes visible in the command prompt window:

c:\unoconv>"C:\Program Files\LibreOffice 4\program\python.exe" unoconv -f pdf tests\document-example.odt
unoconv: RuntimeException during update-indexes phase:
Office probably died. Binary URP bridge disposed during call
Traceback (most recent call last):
  File "unoconv", line 1172, in <module>
    die(exitcode)
  File "unoconv", line 1032, in die
    if convertor.desktop.getCurrentFrame():
uno.DisposedException: Binary URP bridge already disposed

Am I doing something wrong, e.g. the missing environment variable, or is this a bug? Thanks for any help on this.

**Comment by dagwieers** [comment]
Maybe adding `-vvv` to the command line sheds some light to what is going on ?

**Comment by misak1** [comment]
I am also troubled by the same symptoms .

- Windows8 64bit 
- LibreOffice 5.0.3 (LibreOffice_5.0.3_Win_x64.msi)


```
C:\Users\9141-063001>"c:\Program Files\LibreOffice 5\program\python.exe" c:\Users\9141-063001\bin\unoconv-0.7\unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform nt/win32
python 3.3.5 (default, Oct 26 2015, 00:31:34) [MSC v.1800 64 bit (AMD64)]
LibreOffice 5.0.3.2

C:\Users\9141-063001>"c:\Program Files\LibreOffice 5\program\python.exe" c:\Users\9141-063001\bin\unoconv-0.7\unoconv -f pdf c:\Users\9141-063001\bin\unoconv-0.7\tests\document-example.odt
Traceback (most recent call last):
  File "c:\Users\9141-063001\bin\unoconv-0.7\unoconv", line 1349, in <module>
    main()
  File "c:\Users\9141-063001\bin\unoconv-0.7\unoconv", line 1263, in main
    convertor = Convertor()
  File "c:\Users\9141-063001\bin\unoconv-0.7\unoconv", line 777, in __init__
    self.desktop = unosvcmgr.createInstanceWithContext("com.sun.star.frame.Desktop", unocontext)
uno.RuntimeException: Binary URP bridge disposed during call
```

It will attach the log .

```
C:\Users\9141-063001>"c:\Program Files\LibreOffice 5\program\python.exe" -vvv c:\Users\9141-063001\bin\unoconv-0.7\unoconv -f pdf c:\Users\9141-063001\bin\unoconv-0.7\tests\document-example.odt > win8
-64bit_unoconv.log 2>&1
```

[win8-64bit_unoconv.log](https://gist.github.com/misak1/444cb0f08e2519793fb4)
