### ISSUE TITLE
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)

### ISSUE THREAD

**Issue by spotla** [dagwieers/unoconv#258]
unoconv log :

Found pyuno.so in /Applications/LibreOffice.app/Contents/Frameworks
Found soffice in /Applications/LibreOffice.app/Contents/MacOS
Found python in /Applications/LibreOffice.app/Contents/MacOS
Considering /Applications/LibreOffice.app/Contents
Traceback (most recent call last):
  File "/Users/siva/projects/research/unoconv/unoconv", line 1131, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 335, in _uno_import
    raise uno_import_exc
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)

**Comment by dagwieers** [comment]
Sorry, I don't know what this means. You didn't actually provide a lot of information.

What exactly did you run ?
What version of unoconv and LibreOffice are you using ?
How did you install them ?
Did you follow the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) and did it provide you with any clues ?

We need more feedback in order to help you. So if you've got more information, feel free to reopen this ticket.

**Comment by wuzhicms** [comment]
wcj:unoconv wcj$ /Applications/LibreOffice.app/Contents/MacOS/python unoconv -f pdf test.docx
Traceback (most recent call last):
  File "unoconv", line 1320, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 339, in _uno_import
    raise uno_import_exc
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)

**Comment by mauroc** [comment]
I am getting the same error. Just installed unoconv on mac OSX with brew and got that error message when I typed 

unoconf -f cnf myfile.xlsx

(BTW same error if I simply type unoconv without any parameters)

**Comment by pdlug** [comment]
I'm seeing the same issue using LibreOffice 5.1.2.2 and 4.4.7.2 on Mac OS X. I don't have any issues with LibreOffice 4.2.8.2 on Ubuntu or Mac.

The test commands in the README do work for me (e.g., `/Applications/LibreOffice.app/Contents/MacOS/python -c 'import uno, unohelper'`) but I get the same stack trace as the original reporter trying to run `unoconverter` itself.

**Comment by sikko** [comment]
Thanks @pdlug I just downgraded to version 4.2.8.2 and it solved the problem for me. Not ideal, but that'll do for now.

**Comment by risto3** [comment]
Unfortunately now that libreoffice-still-fr has been upgraded to 5.3.5-1 the workaround no longer works.
A durable fix is therefore needed.
Is this confirmed to be isolated to archlinux? if so, we should find a fix to the packaging procedure, pronto.

**Comment by jalevin** [comment]
+1 been trying a bunch of different version. Doesn't work on 5.2.7, 5.3.7

brew install unoconv
/Applications/LibreOffice.app/Contents/Resources/python unoconv -f pdf mydoc.xlsx

> Traceback (most recent call last):
  File "unoconv", line 1350, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 339, in _uno_import
    raise uno_import_exc
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)

>

**Comment by erny** [comment]
I looked into the class, QUIET_UPDATE = 1, so I commented out the import and set the constand manually, but now I get: 
```
Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 1352, in <module>
    from com.sun.star.beans import PropertyValue
  File "/usr/local/bin/unoconv", line 1306, in main
    convertor = Convertor()
  File "/usr/local/bin/unoconv", line 796, in __init__
    self.desktop = unosvcmgr.createInstanceWithContext("com.sun.star.frame.Desktop", unocontext)
uno.RuntimeException: Binary URP bridge disposed during call
```

**Comment by esperienzia** [comment]
I'm working on Heroku using Ubuntu 16.04.

I just found the way to make unconv work (almost) using this selfmade buildback: https://github.com/esperienzia/heroku-buildpack-unoconv-1

Now when i run the unoconv command (even alone), I get:

```
Traceback (most recent call last):
  File "/app/.apt/usr/bin/unoconv", line 1236, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 342, in _uno_import
    raise uno_import_exc
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
```

Someone has news on this?
