### ISSUE TITLE
unoconv: UnoException during export phase

### ISSUE THREAD

**Issue by penalvch** [dagwieers/unoconv#312]
Execute the following in a terminal:
cd ~/Desktop && wget https://bugs.launchpad.net/ubuntu/+source/openoffice.org/+bug/138141/+attachment/2144240/+files/p0p1p2.odg && unoconv --listener && unoconv -f svg p0p1p2.odg && lodraw -nologo p0p1p2.odg p0p1p2.svg

unoconv: UnoException during export phase:
Unable to store document to file:///home/username/Desktop/p0p1p2.svg (ErrCode 2074)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x1ac4018{, supportedInterfaces={com.sun.star.io.XOutputStream,com.sun.star.lang.XTypeProvider}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"impress_svg_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

ProblemType: Bug
DistroRelease: Ubuntu 15.10
Package: unoconv 0.7-1.1
ProcVersionSignature: Ubuntu 4.2.0-23.28-generic 4.2.6
Uname: Linux 4.2.0-23-generic x86_64
ApportVersion: 2.19.1-0ubuntu5
Architecture: amd64
CurrentDesktop: GNOME-Flashback:Unity
Date: Tue Jan 12 23:52:54 2016
InstallationDate: Installed on 2015-12-18 (25 days ago)
InstallationMedia: Ubuntu 15.10 "Wily Werewolf" - Release amd64 (20151021)
PackageArchitecture: all
SourcePackage: unoconv
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by jannewmarch** [comment]
unoconv was working fine for several files until yesterday when it started throwing this error. When I opened the file using LibreOffice it said it was read-only, which hadn't happened before. The directory is read/write. I saw a suggestion to run as root, it just exits when I do that
$unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
LibreOffice 5.1.4.2

**Comment by jannewmarch** [comment]
An update, may be important as signalling what is going on. Today I ran multiple HTML files through unoconv, saving them as .doc files. Then I tried one again and it didn't work. THIS time, when I loaded the file into LibreOffice the title bar showed "LibreOffice Writer/Web" instead of just "LibreOffice Writer". And nearly all of the Save As options had disappeared, including the .doc option - so it died, unable to save in that format. I've been unable to find any info on Writer/Web. This change of mode is happening with files that 4 hours ago were fine, and I haven't changed the files at all.

**Comment by jannewmarch** [comment]
Further update. There is an undocumented feature. If LibreOffice is already open when you open an HTML file, then it can be saved in multiple formats including .doc. If it isn't open, then you can only save in a limited number of formats, not including .doc etc.

**Comment by regebro** [comment]
Is this still an issue?

**Comment by jannewmarch** [comment]
just tried
```
wget https://bugs.launchpad.net/ubuntu/+source/openoffice.org/+bug/138141/+attachment/2144240/+files/p0p1p2.odg && unoconv --listener && unoconv -f svg p0p1p2.odg
```
as in the original error posting and got this:
```
$unoconv -f svg p0p1p2.odg 
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1030, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/newmarch/boxhill/ACS/CyberSecurityMajor/p0p1p2.svg> failed: 0x81a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1191, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1032, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
```
Seems to be a different error!  This is from
```
$unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
LibreOffice 6.0.7.3
```

**Comment by regebro** [comment]
Hm, strange, I can't reproduce that, with exact same versions and file. 
Can you try with the version of unoconv here on github, I should have at least fixed the "During handling of the above exception, another exception occurred" bug.

```
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
LibreOffice 6.0.7.3
```

**Comment by neurino** [comment]
Hello, same version unoconv 0.7 / python 3.6.7 / LibreOffice 6.0.7.3 here, same error.

I noticed that I get the error while trying to save on a samba share, while saving in /tmp and moving then to share works as expected.

Can this be of any help to get this solved?

**Comment by paolobenve** [comment]
$ unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
LibreOffice 6.1.5.2

I'm having this bug:

```
$ sudo /usr/bin/unoconv -f html -o 'vespri.htm' '/var/cache/qumran/anteprima/aree_testi/preghiera/ore/vespri-s-andrea.zip/vespri santAndrea.doc' 
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1030, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/paolo/vespri.html> failed: 0x507(Error Area:Io Class:Access Code:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1191, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1032, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
```

What can I do in order to get unoconv working again?

**Comment by paolobenve** [comment]
after upgrading unoconv to current github version:

```
$ unoconv -vvvvvvvvvvvv -f html -o ~ /media/nas.nfs/Documents/AAAA\ Cornigliano/Foglio\ lavoro\ pulizia\ campetto.odt 
Verbosity set to level 12
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
Input file: /media/nas.nfs/Documents/AAAA Cornigliano/Foglio lavoro pulizia campetto.odt
Selected output format: HTML Document (OpenOffice.org Writer) [.html]
Selected office filter: HTML (StarWriter)
Used doctype: document
Output file: file:///home/paolo.html
unoconv: UnoException during export phase:
Unable to store document to file:///home/paolo.html (Error (com.sun.star.io.IOException){ (com.sun.star.uno.Exception){ Message = (string)"SfxBaseModel::impl_store <file:///home/paolo.html> failed: 0x507(Error Area:Io Class:Access Code:7)", Context = (com.sun.star.uno.XInterface)0x0{} } })

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"HTML (StarWriter)" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x20f5b28{, supportedInterfaces={com.sun.star.io.XOutputStream,com.sun.star.lang.XTypeProvider}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

Why is unable to store the converted document?!?!?

**Comment by Mintaka** [comment]
$ unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
LibreOffice 6.0.7.3

---
unoconv  -f xls -i FilterOptions="59,0,0,1"  myfile.csv -v -o.

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1030, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/m/mywork/myfile.xls> failed: 0x440a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1191, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1032, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode

---
But this command:
unoconv  -v -o ./myfile.xls -f xls -i FilterOptions="59,0,0,1"  myfile.csv 
 
Input file: myfile.csv
Selected output format: Microsoft Excel 97/2000/XP [.xls]
Output file: file:///home/m/mywork/myfile.xls

-------

Also it look like unoconv without exactly specific output have a problem.
