### ISSUE TITLE
Is LibreOffice 6.0 supported?

### ISSUE THREAD

**Issue by int-ua** [dagwieers/unoconv#446]
It doesn't work with 6.0 PPA:

```
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1030, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///tmp/int/1.txt> failed: 0xc10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1191, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1032, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
```

**Comment by int-ua** [comment]
Maybe the reason is that LO decided to [temporarily] drop text export:
https://bugs.documentfoundation.org/show_bug.cgi?id=108597
```
$ localc "-env:UserInstallation=file:///tmp/LibO_Conversion" --convert-to "txt:Text (encoded):UTF8" --headless 1.ods
convert /tmp/int/1.ods -> /tmp/int/1.txt using filter : Text (encoded):UTF8
Error: Please verify input parameters... (SfxBaseModel::impl_store <file:///tmp/int/1.txt> failed: 0xc10)
```

**Comment by elbuenherman** [comment]
Hi..
i had the same problem.. so i just replaced my /etc/bin/unoconv with this following file and it works good

[unoconv.txt](https://github.com/dagwieers/unoconv/files/2288650/unoconv.txt)

Hermann

**Comment by necorobsd** [comment]
After upgrade libreoffice to version 6.0.6 from 6.0.4, all works fine.

**Comment by Wanderish** [comment]
```
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
LibreOffice 6.0.7.3
```
Got LibreOffice 6.0.7.3
Not working on this as well. 
**Getting the following exception on running: unoconv -f doc ieep117.pdf**

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1030, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/maverick/sd/exps/PymuPDF_exps/ieep117.doc> failed: 0x81a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1191, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1032, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode

Also unable to convert to docx, html, xhtml.
Any thoughts, suggestions would be great! Thanks in advance!

**Comment by biligee** [comment]
Same here in Ubuntu 18.04LTS
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
LibreOffice 6.0.7.3

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1189, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 739, in __init__
    unocontext = self.connect(resolver)
  File "/usr/bin/unoconv", line 760, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call

**Comment by biligee** [comment]
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
LibreOffice 6.2.5.2
Also gives:
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1189, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 739, in __init__
    unocontext = self.connect(resolver)
  File "/usr/bin/unoconv", line 760, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call
root@ccjpt249:/var/www/html/data/biligee/files# unoconv text.docx
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1189, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 739, in __init__
    unocontext = self.connect(resolver)
  File "/usr/bin/unoconv", line 760, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call

**Comment by biligee** [comment]
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
LibreOffice 6.2.5.2
also gives errors:
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1189, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 739, in __init__
    unocontext = self.connect(resolver)
  File "/usr/bin/unoconv", line 760, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call
