### ISSUE TITLE
 cannot open directory ./.config/libreoffice/4/user/registry/data

### ISSUE THREAD

**Issue by EKHowick** [dagwieers/unoconv#458]
Today I downloaded the latest version of LibreOffice6 and unoconv.  Using default port 2002 caused the same error others had, so I used -p 12345.  I'm receiving the following error.  I'm using CentOs7.  Does the first traceback mean port 12345 is being used, too?  Does the second traceback refer to HOME, which I set to "." (satisfactory for my test).  The indicated directory exists and is writable....  Thanks.

```
Traceback (most recent call last):
  File "./unoconv", line 809, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.NoConnectException: Connector : couldn't connect to socket (Success)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./unoconv", line 1391, in <module>
    main()
  File "./unoconv", line 1305, in main
    convertor = Convertor()
  File "./unoconv", line 788, in __init__
    unocontext = self.connect(resolver)
  File "./unoconv", line 820, in connect
    product = self.svcmgr.createInstance("com.sun.star.configuration.ConfigurationProvider").createInstanceWithArguments("com.sun.star.configuration.ConfigurationAccess", UnoProps(nodepath="/org.openoffice.Setup/Product"))
uno.RuntimeException: cannot open directory ./.config/libreoffice/4/user/registry/data
```

**Comment by EKHowick** [comment]
Ah-hah.  I changed HOME to /tmp and it works perfectly.
